extraction:
  cpp:
    after_prepare:    # Customizable step used by all languages.
      - wget https://github.com/Kitware/CMake/releases/download/v3.14.5/cmake-3.14.5.tar.gz -O cmake.tar.gz
      - tar -xvzf cmake.tar.gz
      - cd cmake-*/
      - lsb_release -a
      - sed -i '/_qt4_get_version_components/a message(STATUS "QTVersion ${QTVERSION}")' Modules/FindQt4.cmake
      - sed -i '/ file(TO_CMAKE_PATH "${output}" output)/a string(REGEX REPLACE "*\[\\r\\n\]" "" output ${output})")' Modules/FindQt4.cmake
      - ./bootstrap
      - make
      - DESTDIR="$HOME/.local" make install
      - ls $HOME/.local/bin
      - export PATH=$HOME/.local/bin:$PATH
      - cmake --version