extraction:
  cpp:
    prepare:    # Customizable step used by all languages.
      packages:
        - python-pip
    after_prepare:    # Customizable step used by all languages.
      - pip --version
      - which qmake
      - cat /usr/bin/qmake
      - pip2 --version
      - pip install --upgrade pip
      - pip2 install --user --upgrade cmake==3.14.4
      - ls ~/.local/bin
      - export PATH=~/.local/bin:$PATH
      - cmake --version