
    source: rmatmult3_at.spd
    procedure: 0
    loop: 0

    TI=23
    TJ=24
    TK=25
    UI=2
    UJ=3


    permute([1,2,3])
    print
    known(kmax>=3)
    known(imax>=3)
    known(jmax>=3)
    tile(0,3,TI)
    tile(0,3,TJ)
    tile(0,3,TK)
    print
    
    # with all three loops unrolled
    #unroll(0,4,UJ)
    #unroll(0,5,UJ)
    #unroll(0,6,UI)    

    # with only UJ and UI
    unroll(0,5,UJ)
    unroll(0,6,UI)
   
    print
    
