#YAML parsing FILE

#
log-level: debug
iteration: 4
#container: linkedcell
#newton3: enabled
#
Objects:
  CubeGrid:
    0:
      particle-type: 0
      particle-epsilon: 1.
      particle-sigma: 1.
      particle-mass: 1.
      particles-per-Dim: [10,10,10]
      particleSpacing: 0.5
      velocity: [10.,10.,10.]
      center: [5.,5.,5.]
#  CubeGauss:
#    0:
#      particle-type: 0
#      particle-epsilon: 1.
#      particle-sigma: 1.
#      particle-mass: 1.
#      numberOfParticles: 100
#      box-length: [8.,8.,8.]
#      distribution-mean: 2.0
#      distribution-stddev: 5.0
#      velocity: [0.,0.,0.]
#      bottomLeftCorner: [5.,5.,5.]
#  CubeUniform:
#    0:
#      particle-type: 0
#      particle-epsilon: 1.
#      particle-sigma: 1.
#      particle-mass: 1.
#      numberOfParticles: 100
#      box-length: [10.,10.,10.]
#      velocity: [0.,0.,0.]
#      bottomLeftCorner: [5.,5.,5.]
#  Sphere:
#    0:
#      particle-type: 0
#      particle-epsilon: 1.
#      particle-sigma: 1.
#      particle-mass: 1.
#      center: [0.,0.,0.]
#      radius: 10
#      particleSpacing: 0.5
#      firstId: 0
#      velocity: [5.,5.,5.]


