option(CCACHE "Use ccache for accelerated compilation through caching" OFF)
if (CCACHE)
    find_program(CCACHE_FOUND ccache)
    if (CCACHE_FOUND)
        message(STATUS "ccache found, building with ccache")
        set(CMAKE_CXX_COMPILER_LAUNCHER ${CCACHE_FOUND} CACHE STRING "ccache executable")
    else ()
        message(WARNING "ccache not found, building without ccache")
    endif (CCACHE_FOUND)
else ()
    message(STATUS "ccache disabled")
endif (CCACHE)
