option(CCACHE "Use ccache for accellerated compilation through caching" ON)
if (CCACHE)
    find_program(CCACHE_FOUND ccache)
    if (CCACHE_FOUND)
        message(STATUS "ccache found, building with ccache")
        set_property(GLOBAL PROPERTY RULE_LAUNCH_COMPILE ccache)
        set_property(GLOBAL PROPERTY RULE_LAUNCH_LINK ccache)
    else()
        message(WARNING "ccache not found, building without ccache")
    endif (CCACHE_FOUND)
else ()
    message(STATUS "ccache disabled")
endif (CCACHE)
