option(AUTOPAS_INTERNODE_TUNING "Activates distributed tuning in MPI parallel simulations" OFF)

if (AUTOPAS_INTERNODE_TUNING)
    message(STATUS "MPI enabled.")
    find_package(MPI REQUIRED)
    if (NOT ${MPI_CXX_FOUND})
        message(FATAL_ERROR "cxx mpi could not be found")
    endif ()
else ()
    message(STATUS "MPI disabled.")
endif ()
