option(AUTOPAS_OPENMP "Activates OpenMP shared memory parallelization." OFF)

if (ARCHER)
    message(STATUS "archer detected, OpenMP enabled by default, so skipping OpenMP package search")
    set(AUTOPAS_OPENMP ON)
elseif (AUTOPAS_OPENMP)
    message(STATUS "OpenMP enabled.")
    find_package(OpenMP)

    if (NOT OPENMP_FOUND)
        message(FATAL_ERROR "Could not find OpenMP!")
    endif ()
else ()
    message(STATUS "OpenMP disabled.")
endif ()
