option(AUTOPAS_OPENMP "Activates OpenMP shared memory parallelization." OFF)

if (ARCHER)
    message(STATUS "archer detected, OpenMP enabled by default, so skipping OpenMP package search")
    set(AUTOPAS_OPENMP ON)
elseif (AUTOPAS_OPENMP)
    message(STATUS "OpenMP enabled.")
    find_package(OpenMP REQUIRED)

    if (OpenMP_CXX_SPEC_DATE LESS 201511)
        message(FATAL_ERROR "OpenMP version not supported. Required: 4.5+")
    endif ()
else ()
    message(STATUS "OpenMP disabled.")
endif ()
