option(ENABLE_OPENMP "Activates OpenMP shared memory parallelization" OFF)
if (ENABLE_OPENMP)
    if (CMAKE_CXX_COMPILER_ID MATCHES "GNU")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fopenmp")
    elseif (CMAKE_CXX_COMPILER_ID MATCHES "Intel")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -qopenmp")
    else()
        message(SEND_ERROR "Compiler not supportet for OpenMP!")
    endif ()
endif ()