--- old/Dockerfile	2021-07-21 11:52:27.076745285 +0200
+++ new/Dockerfile	2021-07-21 11:52:45.204842728 +0200
@@ -57,4 +57,4 @@
 RUN source /etc/profile && wget https://www.vtk.org/files/release/9.0/VTK-9.0.3.tar.gz -O- | tar xz && mv VTK-9.0.3 vtk && CC=gcc CXX=g++ cmake -S vtk -B vtk_build -DCMAKE_BUILD_TYPE=Release -DINSTALL_CMAKE_PACKAGE_MODULE=ON -DVTK_PYTHON_VERSION=3 -DVTK_USE_MPI=ON -DVTK_GROUP_ENABLE_MPI=YES -DVTK_GROUP_ENABLE_Imaging=DONT_WANT -DVTK_GROUP_ENABLE_Qt=DONT_WANT -DVTK_GROUP_ENABLE_Rendering=DONT_WANT -DVTK_GROUP_ENABLE_StandAlone=WANT -DVTK_GROUP_ENABLE_Views=DONT_WANT -DVTK_GROUP_ENABLE_Web=DONT_WANT -DVTK_ENABLE_LOGGING=OFF && cmake --build vtk_build -j16 && find -L vtk_build -type f -exec readlink -f '{}' \; | xargs file -i | grep 'charset=binary' | grep 'x-executable\|x-archive\|x-sharedlib' | awk -F: '{print $1}' | xargs strip -s && cmake --install vtk_build && rm -rf vtk vtk_build
 
 
-ENTRYPOINT ["/bin/bash", "--rcfile", "/etc/profile", "-l"]
+ENTRYPOINT ["/bin/bash", "--rcfile", "/etc/profile", "-l", "-c"]
