# Workflow for unit tests with archer thread sanitizer
name: archer

# Controls when the action will run.
on:
  push:
    # pushes to master
    branches: [ master ]
  pull_request:
    # PRs to master
    branches: [ master ]

jobs:
  build:
    concurrency:
      group: ${{ github.head_ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    container: autopas/autopas-build-archer

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build everything
        run: |
          mkdir build && cd build
          CXXFLAGS=-Wno-pass-failed CC=clang CXX=clang++ cmake \
            -G Ninja \
            -DCCACHE=ON \
            -DCMAKE_BUILD_TYPE=Release \
            -DAUTOPAS_LOG_ALL=ON \
            -DAUTOPAS_ENABLE_THREAD_SANITIZER=ON \
            -DAUTOPAS_OPENMP=ON \
            -DAUTOPAS_USE_VECTORIZATION=OFF \
            ..
          TSAN_OPTIONS="ignore_noninstrumented_modules=1" entrypoint.sh ninja -j 3
      - name: Run tests
        run: |
          cd build
          TSAN_OPTIONS="ignore_noninstrumented_modules=1" ctest -j 3
      - name: Run examples
        run: |
          cd build/examples
          TSAN_OPTIONS="ignore_noninstrumented_modules=1" ctest -C checkExamples -j 3


