# Workflow for generating, checking, and deploying our doxygen documentation.
name: DocTagChecker

# This Workflow can only run on PRs.
on:
  pull_request:

# abort old runs if a new one is started
concurrency:
  group: ${{ github.head_ref }}-DocTagChecker
  cancel-in-progress: true

jobs:
  DocTagCheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check for missing userdoc updates
        uses: AutoPas/DocTagChecker@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          userDocsDirs: docs/userdoc
          recurseUserDocDirs: true
          docFileExtensions: md
          # c++ files and cmake files
          srcFileExtensions: cpp h txt cmake
