# Workflow for generating, checking, and deploying our doxygen documentation.
name: doxygen

# Controls when the action will run.
on:
  push:
    # pushes to master
    branches: [ master ]
  pull_request:
    # PRs to master
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: autopas/autopas-build-doxygen

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: pwd && ls
      - name: Create Doxygen target via cmake
        run: mkdir build-doxygen && cd $_ && cmake -DAUTOPAS_BUILD_TARGET_DOC=ON ..

      - name: Build documentation
        # Run make to build the doc. Pipe stderr through a subprocess which saves it to warnings.out.
        # Doxygen seems to have stopped throwing warnings from our readme files.
        # If this reappears introduce a `grep -v` filter in the subprocess before tee.
        run: make doc_doxygen 2> >(tee warnings.out >&2)
        working-directory: build-doxygen

      - name: Print warnings
        # Print all warnings collected previously. Exit code depends on number of warnings.
        run: cat warnings.out && exit $(wc -l warnings.out | cut -d' ' -f1)
        working-directory: build-doxygen

#  publish:
#    needs: build
#    runs-on: ubuntu-latest
#    steps:

#      - name: Deploy AutoPas doxygen documentation (only on master)
#        uses: peaceiris/actions-gh-pages@v3.7.2
#        if: github.ref == 'refs/heads/master'
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
#          publish_dir: ./build-doxygen/doc_doxygen/html/
#          destination_dir: doxygen_documentation/git-master/
#          publish_branch: main
#          external_repository: AutoPas/AutoPas.github.io
#          user_name: github-actions[bot]
#          user_email: github-actions[bot]@users.noreply.github.com
